export const COMMENTS = [
  {
    id: 0,
    courseCode: "HW0001",
    usefulness: 8,
    easiness: 10,
    timeinvestment: 10,
    comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    author: "Liew Zi Peng",
    reply: [
      {
        id: 0,
        author: "Liew Zi Peng",
        content: "Study one day get A+",
      },
      {
        id: 1,
        author: "Liew Zi Peng",
        content: "Really Easy",
      },
      {
        id: 2,
        author: "Liew Zi Peng",
        content: "Study one day get A+",
      },
      {
        id: 3,
        author: "Liew Zi Peng",
        content: "Really Easy",
      },
    ],
  },
  {
    id: 0,
    courseCode: "BU8201",
    usefulness: 8,
    easiness: 10,
    timeinvestment: 10,
    comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    author: "Liew Zi Peng",
    reply: [
      {
        id: 0,
        author: "Liew Zi Peng",
        content: "Study one day get A+",
      },
      {
        id: 1,
        author: "Liew Zi Peng",
        content: "Really Easy",
      },
      {
        id: 2,
        author: "Liew Zi Peng",
        content: "Study one day get A+",
      },
      {
        id: 3,
        author: "Liew Zi Peng",
        content: "Really Easy",
      },
    ],
  },
  {
    id: 1,
    courseCode: "BU8201",
    usefulness: 8,
    easiness: 10,
    timeinvestment: 10,
    comment: "Easy A+",
    author: "Liew Zi Peng",
  },
  {
    id: 2,

    courseCode: "BU8201",
    usefulness: 8,
    easiness: 10,
    timeinvestment: 10,
    rating: 5,
    comment: "Easy A+",
    author: "Liew Zi Peng",
  },
  {
    id: 3,

    courseCode: "BU8201",
    usefulness: 8,
    easiness: 10,
    timeinvestment: 10,
    rating: 5,
    comment: "Easy A+",
    author: "Liew Zi Peng",
    reply: [
      {
        id: 0,
        author: "Liew Zi Peng",
        content: "Study one day get A+",
      },
      {
        id: 1,
        author: "Liew Zi Peng",
        content: "Really Easy",
      },
      {
        id: 2,
        author: "Liew Zi Peng",
        content: "Study one day get A+",
      },
      {
        id: 3,
        author: "Liew Zi Peng",
        content: "Really Easy",
      },
    ],
  },
  {
    id: 4,
    courseCode: "CZ2001",
    usefulness: 8,
    easiness: 10,
    timeinvestment: 10,
    rating: 5,
    comment: "Easy A+",
    author: "Liew Zi Peng",
  },
  {
    id: 5,

    courseCode: "CZ2001",
    usefulness: 8,
    easiness: 10,
    timeinvestment: 10,
    rating: 5,
    comment: "Easy A+",
    author: "Liew Zi Peng",
  },
  {
    id: 6,

    courseCode: "CZ2001",
    usefulness: 8,
    easiness: 10,
    timeinvestment: 10,
    rating: 5,
    comment: "Easy A+",
    author: "Liew Zi Peng",
  },
  {
    id: 7,

    courseCode: "CZ2001",
    usefulness: 8,
    easiness: 10,
    timeinvestment: 10,
    rating: 5,
    comment: "Easy A+",
    author: "Liew Zi Peng",
  },
];
