export const COMMENTS = [
  {
    id: 0,
    courseCode: "BU8201",
    usefulness: 8,
    easiness: 10,
    timeinvestment: 10,
    comment: "Easy A+",
    author: "Liew Zi Peng",
  },
  {
    id: 1,
    courseCode: "BU8201",
    usefulness: 8,
    easiness: 10,
    timeinvestment: 10,
    comment: "Easy A+",
    author: "Liew Zi Peng",
  },
  {
    id: 2,
    courseCode: "BU8201",
    rating: 5,
    comment: "Easy A+",
    author: "Liew Zi Peng",
  },
  {
    id: 3,
    courseCode: "BU8201",
    rating: 5,
    comment: "Easy A+",
    author: "Liew Zi Peng",
  },
  {
    id: 4,
    courseCode: "CZ2001",
    rating: 5,
    comment: "Easy A+",
    author: "Liew Zi Peng",
  },
  {
    id: 5,
    courseCode: "CZ2001",
    rating: 5,
    comment: "Easy A+",
    author: "Liew Zi Peng",
  },
  {
    id: 6,
    courseCode: "CZ2001",
    rating: 5,
    comment: "Easy A+",
    author: "Liew Zi Peng",
  },
  {
    id: 7,
    courseCode: "CZ2001",
    rating: 5,
    comment: "Easy A+",
    author: "Liew Zi Peng",
  },
];
