export const COURSES = [
  {
    id: 4,
    courseCode: "HW0001",
    name: "Business Law",
    numberOfAUs: 3,
    prerequisites: "blablabla",
    gradingType: "Letter graded",
    mutuallyExclusive: "AB1201",
    examSchedule: "Not Available",
    averageRating: 6.9,
    usefulness: 8.4,
    easiness: 7.8,
    timeinvestment: 4.4,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
  },
  {
    id: 0,
    courseCode: "BU8201",
    name: "Business Law",
    numberOfAUs: 3,
    prerequisites: "blablabla",
    gradingType: "Letter graded",
    mutuallyExclusive: "AB1201",
    examSchedule: "Not Available",
    averageRating: 6.9,
    usefulness: 8.4,
    easiness: 7.8,
    timeinvestment: 4.4,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
  },
  {
    id: 1,
    courseCode: "CZ2001",
    name: "Algorithms",
    numberOfAUs: 3,
    prerequisites: "blablabla",
    gradingType: "Letter graded",
    mutuallyExclusive: "AB1201",
    examSchedule: "Not Available",
    averageRating: 6.9,
    usefulness: 8.4,
    easiness: 7.8,
    timeinvestment: 4.4,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
  },
  {
    id: 2,
    courseCode: "HP8006",
    name: "Economics",
    numberOfAUs: 3,
    prerequisites: "blablabla",
    gradingType: "Letter graded",
    mutuallyExclusive: "AB1201",
    examSchedule: "Not Available",
    averageRating: 6.9,
    usefulness: 8.4,
    easiness: 7.8,
    timeinvestment: 4.4,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
  },
  {
    id: 3,
    courseCode: "HP6006",
    name: "Management",
    numberOfAUs: 3,
    prerequisites: "blablabla",
    gradingType: "Letter graded",
    mutuallyExclusive: "AB1201",
    examSchedule: "Not Available",
    averageRating: 6.9,
    usefulness: 8.4,
    easiness: 7.8,
    timeinvestment: 4.4,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
  },
];
